---
- block:
    - group: name=sudo state=present
    - copy: content="%sudo ALL=(ALL:ALL) NOPASSWD:ALL" dest=/etc/sudoers.d/sudo mode=0440
    - user: name=neeco groups=sudo
    - user: name=prov groups=sudo password=$6$rounds=656000$TfXvGXbvfGZi2PKG$sy1TD1rvpcx9ePOqGTDw8PipzK95Jklh3sjPMb8K7CF827Es8jiKdy2JhUratQtTruCDhfLfCCGKUapMmwgcd1
  when: ansible_user == 'root'
  tags:
    - common:setup

- name: ======
  authorized_key: user=neeco key={{ item }} state=present
  become: yes
  with_items: "{{ ssh_pub_keys }}"
  tags:
    - common:setup

- name: ======
  set_fact:
    common_popular_package:
      - curl
      - wget
      - git
      - python-pip
  tags:
    - common:setup

- block:
    - apt: update_cache=yes cache_valid_time=86400
      become: yes
      name: ---
    - apt: name={{ item }} state=present
      become: yes
      with_items:
        - python-apt
        - "{{ common_popular_package }}"
      name: ---
  when: ansible_distribution | lower == 'ubuntu'
  tags:
    - common:setup

- block:
    - command: yum clean all
      become: yes
      name: ---
    - yum: name={{ item }} state=present
      become: yes
      with_items:
        - epel-release
        - "{{ common_popular_package }}"
      name: ---
  when: ansible_distribution | lower == 'centos'
  tags:
    - common:setup

- name: ======
  become: yes
  pip: name=pip state=latest
  tags:
    - common:setup

- name: ======
  become: yes
  hostname: name={{ custom_hostname | default(inventory_hostname) }}
  tags:
    - common:hostname