image: 5003/centos-ansible-ci:2.2.x
pipelines:
  default:
    - step:
        script:
          - COMMON_PARAM="--verbose --extra-vars ansible_ssh_pass=$PROV_PASS"
          - PARAM="$COMMON_PARAM --limit neeco --tags common:setup,common:hostname" make play
          - PARAM="$COMMON_PARAM --limit neeco --tags docker:engine,docker:compose" make play
          - PARAM="$COMMON_PARAM --limit neeco --tags production" make play
          - PARAM="$COMMON_PARAM --limit neec.xyz --tags rancher:server --extra-vars server_url=http://neec.xyz" make play
          - PARAM="$COMMON_PARAM --limit neec.ooo --tags rancher:agent --extra-vars server_url=http://neec.xyz" make play