image: 5003/centos-ansible-ci:2.1.x
pipelines:
  default:
    - step:
        script:
          - COMMON_PARAM="--verbose --limit neeco --extra-vars ansible_ssh_pass=$PROV_PASS"
          - PARAM="$COMMON_PARAM --tags common:setup,common:hostname" make play
          - PARAM="$COMMON_PARAM --tags docker:engine,docker:compose,docker:daemon" make play
          - PARAM="$COMMON_PARAM --tags production" make play