image: 5003/centos-ansible-ci:2.1.x
pipelines:
  default:
    - step:
        script:
          - PARAM="--verbose --user prov --extra-vars ansible_ssh_pass=$PROV_PASS"
          - PARAM="--limit neeco --tags common:setup,common:hostname,docker:engine,docker:compose $PARAM" make play