---
- block:
    - shell: ufw disable && iptables -F && iptables -X && ufw enable
      become: yes
      name: ---
    - ufw: state=enabled policy=deny
      become: yes
      name: ---
    - ufw: state=enabled policy=allow direction=outgoing
      become: yes
      name: ---
    - ufw: rule=allow port={{ item }} proto=tcp
      become: yes
      with_items: "{{ allowed_proto_tcp }}"
      name: ---
  when: ansible_distribution | lower == 'ubuntu'
  tags:
    - firewall:setup

- block:
    - firewalld: port={{ item }}/tcp permanent=yes state=enabled immediate=yes
      become: yes
      with_items: "{{ allowed_proto_tcp }}"
      name: ---
  when: ansible_distribution | lower == 'centos'
  tags:
    - firewall:setup